rules:
  indentation:
    - 2
    - size: 2
  nesting-depth:
    - 4
    - max-depth: 4
  no-transition-all:
    - 0
  property-sort-order:
    - 1
    - order: concentric
  no-color-literals:
    - 1
    - allow-rgba: true
  hex-notation:
    - 1
    - style: lowercase
  leading-zero:
    - 2
    - include: true
